### ISSUE TITLE
请问，为什么被监控的机器只能显示32个？

### ISSUE THREAD

**Issue by xkwy521** [tenyue/ServerStatus#11]
config.json里设置了50多台机器，但是只能显示32个！修改什么地方才能显示全部的？

**Comment by tenyue** [comment]
已经修改上线为128~重新pull下server的代码：

> 修改/server/src/network.h文件中
'NET_MAX_CLIENTS = 32'

**Comment by cppla** [comment]
或者自行添加host映射，比如说监测本地三大运行商IP等。
