### ISSUE TITLE
关于Load 1，5，15

### ISSUE THREAD

**Issue by Rhilip** [tenyue/ServerStatus#12]
在添加`Load1, 5, 15`时未考虑向前兼容。本人目前服务器端仍然停留在较早的commit 23d028f59508822b2d75feea24727c2fe087276c 中，遇到这种情况就特别麻烦，需要同时升级服务器以及多处客户端。因为在早前客户端向服务器中只提交load字段，但是在目前的master中，这个字段被拆分成了 load_1, load_5, load_15,，且没有保留原先的 load，建议：

重新添加load字段，保持向前兼容一段时间。
```
array['load'] = array['load_1'] = Load_1
```
或者直接在客户端拼接load1, 5, 15 成一个字段放在 array['load']中提交给服务器。然后网页直接显示即可，这样也不需要在前端拼接。而且服务器端也不需要重新编译。
```
array['load'] = ",".join([str(Load_1),str(Load_5),str(Load_15)])
```

--------------------------

此外，直接对os.getloadavg()进行解包，而不是定义一堆获取函数是不是会好些？
```
Load_1, Load_5, Load_15 = os.getloadavg()
```

**Comment by tenyue** [comment]
@Rhilip  感谢，当初考虑是方便他人做前端扩展（eg: https://tz.cloudcpp.com/json/stats.json），另外计划shell自动安装服务端，所以这个把load_1 and load_5 and load_15 给拆分了。。。

第二个问题：还是老手给力，python本是优雅的语言，被我写复杂了。马上更正，😄

**Comment by Rhilip** [comment]
感谢回复。关于解包的话我还是建议构建专门函数，考虑到os.getloadavg()只有在linux上才有。
建议在psutils上采取
```
def get_load():
	try:
		return os.getloadavg()
	except:
		return (-1.0, -1.0, -1.0)
```

下面以`Load_1, Load_5, Load_15 = get_load()` 的形式解包

**Comment by tenyue** [comment]
@Rhilip 已经修复， 没用异常，直接 判断的操作系统类型。。。
