### ISSUE TITLE
如何突破监控服务器总数量的限制，目前只能监控32台服务器

### ISSUE THREAD

**Issue by xieshenglin** [tenyue/ServerStatus#6]
如何突破监控服务器总数量的限制？经测试，目前只能监控32台服务器，之后增加再多，web页面也只显示前面的32台服务器。

**Comment by tenyue** [comment]
老外的代码应该不会出这么明显的bug呀，会尽快调试 ， web目录下的 stat.json 传输的服务器状态大于32台吗？@xieshenglin

**Comment by mr-cn** [comment]
修改/server/src/network.h文件中

'NET_MAX_CLIENTS = 32'

**Comment by tenyue** [comment]
赞，三楼 @mr-cn
