### ISSUE TITLE
centos6 无法正常使用

### ISSUE THREAD

**Issue by inke3c** [tenyue/ServerStatus#7]
centos6 使用 pyenv 已经升级的 python2.7.6或者python2.7.13，ServerStatus 的 WEB 界面出现打开立刻关闭，重复执行打开关闭，centos7正常使用。

**Comment by tenyue** [comment]
我这边正常下，你的什么版本 ?  @inke3c

**Comment by inke3c** [comment]
老哥我的环境是这样的
[root@host ~]# pyenv version
2.7.6 (set by /root/.pyenv/version)

[root@host ~]# uname -a
Linux host.localdomain 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tenyue** [comment]
@inke3c 你用的是普通版把，换成通用版本【client-psutil.py】。

**Comment by inke3c** [comment]
@tenyue  老哥，我把系统 python 升级2.7就好了，pyenv 好像是不行。

**Comment by cppla** [comment]
在线365天，显示成   31536000    秒吗   😄

**Comment by ghost** [comment]
W天 X:Y:Z 这样子显示啊

**Comment by cppla** [comment]
可以。
