### ISSUE TITLE
报错无法启动服务端

### ISSUE THREAD

**Issue by mr-cn** [tenyue/ServerStatus#8]
# ./sergate
[net]: failed to create socket with domain 10 and type 1 (97 'Address family not supported by protocol')
[server]: Bound to :35601

Centos 6.8

**Comment by tenyue** [comment]
检查端口，检查domain ， 读readme @mr-cn

**Comment by mr-cn** [comment]
已通过netstat检查了端口，并无占用。
根据错误提示我grep -r "domain" *.*找过了domain和10这两个关键词，没搜到相关内容。
config.json中的host已正确配置。
文档并未提及，请问domain是在哪里设置？

**Comment by mr-cn** [comment]
已解决。
原因是Socket绑定了阿里云默认配置的IPV6，但ipv6实际无法使用？
解决方法：system.c
1077行：改为`if(1 || bindaddr.type&NETTYPE_IPV4)`
1093行：改为`if(0 && bindaddr.type&NETTYPE_IPV6)`

**Comment by tenyue** [comment]
楼主也是大神呀， 哈哈。可以使用，但是国内ipv6使用的比较少， 就没过多测试。 @mr-cn

**Comment by tenyue** [comment]
下次更新把这个代码会把这个屏蔽加进去。。欢迎来push代码。。我fork的老外的项目。。 @mr-cn
