### ISSUE TITLE
节点上限

### ISSUE THREAD

**Issue by mmmwhy** [tenyue/ServerStatus#9]
站点添加79个节点之后，就不能再继续添加了。
系统存在数量上限吗？

**Comment by tenyue** [comment]
修改/server/src/network.h文件中

'NET_MAX_CLIENTS = 32'

**Comment by tenyue** [comment]
@mmmwhy 如果编辑后没问题，告诉我一下，我合并下代码。

**Comment by mmmwhy** [comment]
可以用了，多谢
